# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.11
#
# <auto-generated>
#
# Generated from file `SimpleObject.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module Demo
_M_Demo = Ice.openModule('Demo')
__name__ = 'Demo'

_M_Demo._t_SimpleObject = IcePy.defineValue('::Demo::SimpleObject', Ice.Value, -1, (), False, True, None, ())

if 'SimpleObjectPrx' not in _M_Demo.__dict__:
    _M_Demo.SimpleObjectPrx = Ice.createTempClass()
    class SimpleObjectPrx(Ice.ObjectPrx):

        def setState(self, state, context=None):
            return _M_Demo.SimpleObject._op_setState.invoke(self, ((state, ), context))

        def setStateAsync(self, state, context=None):
            return _M_Demo.SimpleObject._op_setState.invokeAsync(self, ((state, ), context))

        def begin_setState(self, state, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.SimpleObject._op_setState.begin(self, ((state, ), _response, _ex, _sent, context))

        def end_setState(self, _r):
            return _M_Demo.SimpleObject._op_setState.end(self, _r)

        def getState(self, context=None):
            return _M_Demo.SimpleObject._op_getState.invoke(self, ((), context))

        def getStateAsync(self, context=None):
            return _M_Demo.SimpleObject._op_getState.invokeAsync(self, ((), context))

        def begin_getState(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.SimpleObject._op_getState.begin(self, ((), _response, _ex, _sent, context))

        def end_getState(self, _r):
            return _M_Demo.SimpleObject._op_getState.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_Demo.SimpleObjectPrx.ice_checkedCast(proxy, '::Demo::SimpleObject', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_Demo.SimpleObjectPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::Demo::SimpleObject'
    _M_Demo._t_SimpleObjectPrx = IcePy.defineProxy('::Demo::SimpleObject', SimpleObjectPrx)

    _M_Demo.SimpleObjectPrx = SimpleObjectPrx
    del SimpleObjectPrx

    _M_Demo.SimpleObject = Ice.createTempClass()
    class SimpleObject(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Demo::SimpleObject', '::Ice::Object')

        def ice_id(self, current=None):
            return '::Demo::SimpleObject'

        @staticmethod
        def ice_staticId():
            return '::Demo::SimpleObject'

        def setState(self, state, current=None):
            raise NotImplementedError("servant method 'setState' not implemented")

        def getState(self, current=None):
            raise NotImplementedError("servant method 'getState' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_Demo._t_SimpleObjectDisp)

        __repr__ = __str__

    _M_Demo._t_SimpleObjectDisp = IcePy.defineClass('::Demo::SimpleObject', SimpleObject, (), None, ())
    SimpleObject._ice_type = _M_Demo._t_SimpleObjectDisp

    SimpleObject._op_setState = IcePy.Operation('setState', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), None, ())
    SimpleObject._op_getState = IcePy.Operation('getState', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_string, False, 0), ())

    _M_Demo.SimpleObject = SimpleObject
    del SimpleObject

# End of module Demo
